spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: JwtAuthFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: JwtAuthFilter
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: REPLACE_WITH_YOUR_JWT_SECRET
